#include <opencv2/opencv.hpp>
extern void matop();
extern void matop2();
extern void matop3();
extern void matop4();
extern auto matop5() -> void;
extern void matop6();
extern void camera_in();
extern void video_in();
extern void video_out();
extern void drawLines();
extern void drawPolys();
extern void keyboard_event();
extern void mouse_event();
extern void trackbar_event();
extern void mask_setTo();
extern void mask_copyTo();
extern void brightness1();
extern void brightness3();
extern void brightness4();
extern void show_hist();
extern void histogram_streching();
extern void histogram_equlaization();
extern void arithemtic();
extern void logical();
extern void filter_embossing();
extern void bluring_mean();
extern void bluring_gaussian();
extern void unsharp_mask();
extern void noise_gapussian();
extern void filter_bilaterial();
extern void filter_median();
extern void affine_transform();
extern void affine_translation();
int main()
{
    std::cout << "Hello OpenCV " << CV_VERSION << std::endl;
    //::matop();
    //::matop2();
    //::matop3();
    //::matop4();
    //::matop5();
    //::matop6();
    //::camera_in();
    //::video_in();
    //::video_out();
    //::drawLines();
    //::drawPolys();
    //::keyboard_event();
    //::mouse_event();
    //::trackbar_event();
    //(*::mask_setTo)();
    //::mask_copyTo();
    //::brightness1();
    //::brightness3();
    //::brightness4();
    //::show_hist();
    //::histogram_streching();
    //::histogram_equlaization();
    //::arithemtic();
    //::logical();
    //::filter_embossing();
    //::bluring_mean();
    //::bluring_gaussian();
    //::unsharp_mask();
    //::noise_gapussian();
    //::filter_bilaterial();
    //::filter_median();
    //::affine_transform();
    ::affine_translation();
    return 0;
}
